# Generated by Django 6.0.5 on 2026-05-22 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SourceWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('source_type', models.CharField(choices=[('central', '一級機關'), ('department', '二級機關'), ('district', '區公所'), ('other', '其他')], default='other', max_length=32)),
                ('url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tag_type', models.CharField(choices=[('region', 'region'), ('activity_type', 'activity_type'), ('audience', 'audience'), ('cost', 'cost'), ('discount', 'discount'), ('time', 'time')], max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['tag_type', 'name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'tag_type'), name='unique_tag_name_type')],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', '上架中'), ('inactive', '已下架'), ('draft', '草稿')], default='draft', max_length=10)),
                ('source_agency', models.CharField(blank=True, max_length=200)),
                ('source_url', models.URLField(blank=True, max_length=1000)),
                ('raw_content', models.TextField(blank=True)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('image_url', models.URLField(blank=True)),
                ('is_free', models.BooleanField(default=False)),
                ('requires_registration', models.BooleanField(default=False)),
                ('fee_description', models.CharField(blank=True, max_length=300)),
                ('registration_info', models.TextField(blank=True)),
                ('has_citizen_card_discount', models.BooleanField(default=False)),
                ('citizen_card_note', models.CharField(blank=True, max_length=300)),
                ('ai_summary', models.TextField(blank=True)),
                ('ai_confidence', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_website', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='events.sourcewebsite')),
                ('tags', models.ManyToManyField(blank=True, related_name='activities', to='events.tag')),
            ],
            options={
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_user_id', models.CharField(max_length=64, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('push_enabled', models.BooleanField(default=True)),
                ('default_remind_before_days', models.PositiveIntegerField(default=1)),
                ('has_citizen_card', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_tags', models.ManyToManyField(blank=True, related_name='preferred_by', to='events.tag')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remind_before_days', models.PositiveIntegerField(default=1)),
                ('is_notified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='events.activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='events.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('view_card', 'view_card'), ('interested', 'interested'), ('not_interested', 'not_interested'), ('subscribe', 'subscribe'), ('unsubscribe', 'unsubscribe'), ('how_to_go', 'how_to_go'), ('add_calendar', 'add_calendar'), ('view_more', 'view_more'), ('citizen_card_click', 'citizen_card_click')], max_length=64)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to='events.activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='events.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['start_date'], name='events_acti_start_d_0257d9_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['district'], name='events_acti_distric_f322e5_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['status'], name='events_acti_status_3bf264_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['source_website'], name='events_acti_source__927690_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('user', 'activity')},
        ),
    ]
