# Generated by Django 5.2.14 on 2026-05-30 17:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_activity_ocr_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "run_type",
                    models.CharField(
                        choices=[
                            ("crawler", "crawler"),
                            ("json_import", "json_import"),
                            ("ai_tag_audit", "ai_tag_audit"),
                        ],
                        default="crawler",
                        max_length=32,
                    ),
                ),
                ("source", models.CharField(blank=True, max_length=100)),
                ("input_path", models.CharField(blank=True, max_length=1000)),
                ("created_count", models.PositiveIntegerField(default=0)),
                ("updated_count", models.PositiveIntegerField(default=0)),
                ("skipped_count", models.PositiveIntegerField(default=0)),
                ("failed_count", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "running"),
                            ("success", "success"),
                            ("partial", "partial"),
                            ("failed", "failed"),
                        ],
                        default="running",
                        max_length=16,
                    ),
                ),
                ("error_summary", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, null=True)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="AIProcessingLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_user_id", models.CharField(blank=True, max_length=64)),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("condition_extract", "condition_extract"),
                            ("rerank", "rerank"),
                            ("tagging", "tagging"),
                            ("ocr", "ocr"),
                        ],
                        max_length=32,
                    ),
                ),
                ("model", models.CharField(blank=True, max_length=100)),
                ("prompt_version", models.CharField(blank=True, max_length=32)),
                ("input_summary", models.TextField(blank=True)),
                ("output_json", models.JSONField(blank=True, null=True)),
                ("latency_ms", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "success"), ("failed", "failed")],
                        max_length=16,
                    ),
                ),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "activity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_logs",
                        to="events.activity",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PushCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField(blank=True)),
                ("audience_rule", models.JSONField(blank=True, null=True)),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "draft"),
                            ("scheduled", "scheduled"),
                            ("sending", "sending"),
                            ("sent", "sent"),
                            ("failed", "failed"),
                            ("cancelled", "cancelled"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "activity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="push_campaigns",
                        to="events.activity",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PushDeliveryLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("sent", "sent"),
                            ("failed", "failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("line_response", models.TextField(blank=True)),
                ("error_message", models.TextField(blank=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "activity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="push_delivery_logs",
                        to="events.activity",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_logs",
                        to="events.pushcampaign",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="push_delivery_logs",
                        to="events.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ActivityAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=1000)),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("poster", "poster"),
                            ("main_visual", "main_visual"),
                            ("activity_photo", "activity_photo"),
                            ("other", "other"),
                        ],
                        default="other",
                        max_length=32,
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("ocr_eligible", models.BooleanField(default=False)),
                ("quality_warning", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="events.activity",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_primary", "-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("activity", "url"), name="unique_activity_asset_url"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ActivityTagSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag_name", models.CharField(max_length=100)),
                (
                    "tag_type",
                    models.CharField(
                        choices=[
                            ("region", "region"),
                            ("activity_type", "activity_type"),
                            ("audience", "audience"),
                            ("cost", "cost"),
                            ("discount", "discount"),
                            ("time", "time"),
                        ],
                        max_length=32,
                    ),
                ),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("reason", models.TextField(blank=True)),
                ("source", models.CharField(default="ai", max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("approved", "approved"),
                            ("rejected", "rejected"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tag_suggestions",
                        to="events.activity",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_suggestions",
                        to="events.tag",
                    ),
                ),
            ],
            options={
                "ordering": ["status", "-confidence", "-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("activity", "tag_name", "tag_type", "source"),
                        name="unique_activity_tag_suggestion",
                    )
                ],
            },
        ),
    ]
