# Generated by Django 5.2.14 on 2026-05-31 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_importrun_aiprocessinglog_pushcampaign_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="source_item_id",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                fields=["source_key", "source_item_id"],
                name="events_acti_source__f6e028_idx",
            ),
        ),
    ]
