# Generated by Django 5.2.14 on 2026-05-31 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_activity_source_item_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="last_recommend_pushed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="recommend_push_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="recommend_push_interval_days",
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name="aiprocessinglog",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("condition_extract", "condition_extract"),
                    ("rerank", "rerank"),
                    ("summary", "summary"),
                    ("tagging", "tagging"),
                    ("ocr", "ocr"),
                ],
                max_length=32,
            ),
        ),
    ]
