# Generated by Django 5.2.14 on 2026-05-31 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_userprofile_last_recommend_pushed_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.CharField(max_length=100)),
                ("old_value", models.TextField(blank=True)),
                ("new_value", models.TextField(blank=True)),
                ("source", models.CharField(blank=True, max_length=100)),
                ("notify_required", models.BooleanField(default=False)),
                ("notified_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AdminAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("actor", models.CharField(default="local_admin", max_length=200)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create_activity", "create_activity"),
                            ("update_activity", "update_activity"),
                            ("set_status", "set_status"),
                            ("tag_approve", "tag_approve"),
                            ("tag_reject", "tag_reject"),
                            ("queue_crawl_job", "queue_crawl_job"),
                        ],
                        max_length=64,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CrawlJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "queued"),
                            ("running", "running"),
                            ("success", "success"),
                            ("partial", "partial"),
                            ("failed", "failed"),
                            ("cancelled", "cancelled"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("source", models.CharField(blank=True, max_length=100)),
                ("options", models.JSONField(blank=True, null=True)),
                ("output_path", models.CharField(blank=True, max_length=1000)),
                ("created_by", models.CharField(blank=True, max_length=200)),
                ("error_summary", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CrawlTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_key", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "queued"),
                            ("running", "running"),
                            ("success", "success"),
                            ("partial", "partial"),
                            ("failed", "failed"),
                            ("cancelled", "cancelled"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("attempted_count", models.PositiveIntegerField(default=0)),
                ("created_count", models.PositiveIntegerField(default=0)),
                ("updated_count", models.PositiveIntegerField(default=0)),
                ("skipped_count", models.PositiveIntegerField(default=0)),
                ("failed_count", models.PositiveIntegerField(default=0)),
                ("error_summary", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["source_key"],
            },
        ),
        migrations.AddField(
            model_name="activity",
            name="content_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="activity",
            name="last_seen_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="manual_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="manual_overrides",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="manual_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="activity",
            name="organizer",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="activity",
            name="raw_html_path",
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="activity",
            name="registration_url",
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="pushdeliverylog",
            name="dedupe_key",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="pushdeliverylog",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("campaign", "campaign"),
                    ("recommendation", "recommendation"),
                    ("subscription_reminder", "subscription_reminder"),
                    ("activity_change", "activity_change"),
                ],
                default="campaign",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="last_notified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="status",
            field=models.CharField(
                choices=[("active", "active"), ("cancelled", "cancelled")],
                default="active",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="importrun",
            name="run_type",
            field=models.CharField(
                choices=[
                    ("crawler", "crawler"),
                    ("json_import", "json_import"),
                    ("ai_tag_audit", "ai_tag_audit"),
                    ("crawler_queue", "crawler_queue"),
                ],
                default="crawler",
                max_length=32,
            ),
        ),
        migrations.AddIndex(
            model_name="pushdeliverylog",
            index=models.Index(
                fields=["notification_type", "dedupe_key"],
                name="events_push_notific_43d5d1_idx",
            ),
        ),
        migrations.AddField(
            model_name="activitychangelog",
            name="activity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="change_logs",
                to="events.activity",
            ),
        ),
        migrations.AddField(
            model_name="adminauditlog",
            name="activity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="admin_audit_logs",
                to="events.activity",
            ),
        ),
        migrations.AddField(
            model_name="crawljob",
            name="import_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="crawl_jobs",
                to="events.importrun",
            ),
        ),
        migrations.AddField(
            model_name="crawltask",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="events.crawljob",
            ),
        ),
        migrations.AddIndex(
            model_name="activitychangelog",
            index=models.Index(
                fields=["notify_required", "notified_at"],
                name="events_acti_notify__7ae780_idx",
            ),
        ),
    ]
