# Generated by Django 5.2.14 on 2026-06-03 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0008_activitychangelog_adminauditlog_crawljob_crawltask_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actionlog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("view_card", "view_card"),
                    ("view_detail", "view_detail"),
                    ("interested", "interested"),
                    ("not_interested", "not_interested"),
                    ("subscribe", "subscribe"),
                    ("unsubscribe", "unsubscribe"),
                    ("how_to_go", "how_to_go"),
                    ("add_calendar", "add_calendar"),
                    ("view_more", "view_more"),
                    ("citizen_card_click", "citizen_card_click"),
                ],
                max_length=64,
            ),
        ),
        migrations.CreateModel(
            name="LineConversationState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("intent", models.CharField(blank=True, max_length=32)),
                ("last_query", models.CharField(blank=True, max_length=300)),
                ("conditions", models.JSONField(blank=True, null=True)),
                ("last_activity_ids", models.JSONField(blank=True, null=True)),
                ("offset", models.PositiveIntegerField(default=0)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversation_state",
                        to="events.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="OperationJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("ai_tag", "ai_tag"),
                            ("ocr", "ocr"),
                            ("summary", "summary"),
                            ("push", "push"),
                            ("crawler", "crawler"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "queued"),
                            ("running", "running"),
                            ("success", "success"),
                            ("partial", "partial"),
                            ("failed", "failed"),
                            ("cancelled", "cancelled"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("total_count", models.PositiveIntegerField(default=0)),
                ("processed_count", models.PositiveIntegerField(default=0)),
                ("success_count", models.PositiveIntegerField(default=0)),
                ("failed_count", models.PositiveIntegerField(default=0)),
                ("skipped_count", models.PositiveIntegerField(default=0)),
                ("current_label", models.CharField(blank=True, max_length=300)),
                ("progress_message", models.TextField(blank=True)),
                ("error_summary", models.TextField(blank=True)),
                ("options", models.JSONField(blank=True, null=True)),
                ("result_summary", models.JSONField(blank=True, null=True)),
                ("created_by", models.CharField(blank=True, max_length=200)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["job_type", "status"],
                        name="events_oper_job_typ_56f546_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="events_oper_created_b46f3d_idx"
                    ),
                ],
            },
        ),
    ]
