# Generated by Django 5.2.14 on 2026-06-04 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0009_alter_actionlog_action_type_lineconversationstate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="official_link_checked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="official_link_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="official_link_status",
            field=models.CharField(blank=True, default="unknown", max_length=32),
        ),
        migrations.AlterField(
            model_name="aiprocessinglog",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("condition_extract", "condition_extract"),
                    ("rerank", "rerank"),
                    ("summary", "summary"),
                    ("tagging", "tagging"),
                    ("search_profile", "search_profile"),
                    ("link_check", "link_check"),
                    ("ocr", "ocr"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="operationjob",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("ai_tag", "ai_tag"),
                    ("ocr", "ocr"),
                    ("summary", "summary"),
                    ("push", "push"),
                    ("crawler", "crawler"),
                    ("link_check", "link_check"),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="ActivitySearchProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("search_text", models.TextField(blank=True)),
                ("keywords", models.JSONField(blank=True, null=True)),
                ("topics", models.JSONField(blank=True, null=True)),
                ("synonyms", models.JSONField(blank=True, null=True)),
                ("source_hash", models.CharField(blank=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("success", "success"),
                            ("failed", "failed"),
                            ("stale", "stale"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("error", models.TextField(blank=True)),
                ("provider_model", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "activity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_profile",
                        to="events.activity",
                    ),
                ),
            ],
            options={
                "ordering": ["activity_id"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="events_acti_status_9f9df2_idx"
                    ),
                    models.Index(
                        fields=["source_hash"], name="events_acti_source__f22d00_idx"
                    ),
                ],
            },
        ),
    ]
