# Generated by Django 5.2.7 on 2026-06-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_activity_fee_type_mixed'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='citizen_birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='citizen_card_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='citizen_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='citizen_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
