# Generated by Django 5.2.7 on 2026-06-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_citizencarddata_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='action_type',
            field=models.CharField(choices=[('view_card', 'view_card'), ('view_detail', 'view_detail'), ('interested', 'interested'), ('not_interested', 'not_interested'), ('subscribe', 'subscribe'), ('unsubscribe', 'unsubscribe'), ('how_to_go', 'how_to_go'), ('add_calendar', 'add_calendar'), ('view_more', 'view_more'), ('citizen_card_click', 'citizen_card_click'), ('citizen_card_bind', 'citizen_card_bind')], max_length=64),
        ),
    ]
