# Generated by Django 5.2.7 on 2026-05-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activtiy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='活動名稱')),
                ('description', models.TextField(blank=True, verbose_name='活動說明')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='活動地點')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='開始時間')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='結束時間')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('inactive', '已下架'), ('active', '已上架')], default='draft', max_length=10, verbose_name='狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '活動',
                'verbose_name_plural': '活動管理',
            },
        ),
    ]
