activity_keywords:
  - "活動"
  - "課程"
  - "講座"
  - "展覽"
  - "音樂會"
  - "市集"
  - "嘉年華"
  - "比賽"
  - "體驗"
  - "工作坊"
  - "演出"
  - "表演"
  - "報名"
  - "開放報名"
  - "開放參加"
  - "親子"
  - "巡演"
  - "節"
  - "季"
  - "營隊"
  - "夏令營"
  - "導覽"
  - "小旅行"
  - "手作"
  - "論壇"
  - "說明會"
  - "成果發表"

non_activity_keywords:
  - "公告"
  - "公示送達"
  - "失物招領"
  - "補助計畫"
  - "申請"
  - "決算"
  - "財報"
  - "罰鍰"
  - "徵才"
  - "採購"
  - "法規"
  - "休館公告"
  - "開館事宜"
  - "工廠校正"
  - "營運調查"
  - "公司登記"
  - "商業登記"
  - "政策宣導"
  - "稅務"
  - "違規"
  - "裁罰"
